# Basic Site Settings
locale: "en-US"
title: "Blankybby"
title_separator: "|"
description: "The spellbook"
url: https://blankybby.github.io/
repository: "blankybby/blankybby.github.io"

# Site Author
author name: "Blinkybby"
author bio: "Wizardess in training"
author location: "United States of America, North American Continent, Planet Earth/Terra, 3rd rock from the Sun/Sol system, Milky Way galaxy, the Local Group, Virgo Supercluster, Laniakea Supercluster, within our Universe (which one?)"

# Socials
youtube: "https://www.youtube.com/@blankybby"
twitch: "https://www.twitch.tv/blankybby"
instagram: "https://www.instagram.com/blankybby/"
x: "https://x.com/blankybby"
tiktok: "https://www.tiktok.com/@qtblankybby"
reddit: "https://www.reddit.com/user/Maleficent-Dish-6595/"

# Seo stuff
google_site_verification:
bing_site_verification:
alexa_site_verification:
yandex_site_verification:

# Reading
encoding: "utf-8"
